ckan/ckanext-xloader

- .travis.yml
- bin/travis-build.bash
- bin/travis-run.sh
- ckanext/xloader/jobs.py
- ckanext/xloader/loader.py
- ckanext/xloader/tests/samples/german_sample.csv
- ckanext/xloader/tests/test_loader.py
- ckanext/xloader/tests/util.py
- requirements.txt
- test.ini
> Support unicode headers in loader

- README.rst
- ckanext/xloader/jobs.py
- ckanext/xloader/tests/test_jobs.py
Logs the file size. This is helpful to debug e.g.
```
2018-03-23 17:42:18,374 INFO  [4b5ab067-2fa3-4def-8718-75a599b90103] Fetching from: http://data-cdfw.opendata.arcgis.com/datasets/b8694fc017114db891bdf5b8d0627ccf_1.csv
2018-03-23 17:42:20,561 INFO  [4b5ab067-2fa3-4def-8718-75a599b90103] Downloaded ok - 29.0 MB
2018-03-23 17:42:20,566 INFO  [4b5ab067-2fa3-4def-8718-75a599b90103] File hash: d40291390cd502b99e7d1f71fe6f73b4
```
> Log the file size

- ckanext/xloader/jobs.py
- ckanext/xloader/tests/test_jobs.py
e.g. As seen on this site: https://data-cdfw.opendata.arcgis.com/datasets
```
curl -i http://data-cdfw.opendata.arcgis.com/datasets/1aa5a6663e8e440eaf370175c1b641c1_0.csv
HTTP/1.1 202 Accepted
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Wed, 04 Apr 2018 12:52:33 GMT
ETag: W/"48-WZQqBBarL9Mh/CeprT/VX6sCMLQ"
Server: openresty
Strict-Transport-Security: max-age=15724800; includeSubDomains;
X-Powered-By: Express
Content-Length: 72
Connection: keep-alive
{"processingTime":"8.716 seconds","status":"Processing","generating":{}}
$ curl -I http://data-cdfw.opendata.arcgis.com/datasets/1aa5a6663e8e440eaf370175c1b641c1_0.csv
HTTP/1.1 200 OK
Content-disposition: attachment; filename=Vegetation__Clear_Creek_Monocline_Ridge_%5Bds995%5D.csv
Content-Type: text/csv; …
```
> Do retries when an arcgis server gives a 202 response (indicating its preparing the CSV file)

- ckanext/xloader/controllers.py
Compatibility with this change:
https://github.com/ckan/ckan/pull/4062/files#diff-62490c204273f8269b55ecbe12446d09R4
on master, slated for CKAN 2.9.
Related to: https://github.com/ckan/ckan/issues/4332
> Compatibility with latest ckan master template

- ckanext/xloader/action.py
Which is convenient from a browser
> Make xloader_status action available to GET (not just POST)

- ckanext/xloader/jobs.py
This is a tiny change that just changes the error-messages to be less confusing (because it was to me 😅 )
> refactor error-message to mention xloader instead of datapusher

- ckanext/xloader/cli.py
This is a suggestion to fix #56
> 56 keep processing the remaining resources when an error occurs

- ckanext/xloader/jobs.py
- ckanext/xloader/loader.py
- ckanext/xloader/tests/test_jobs.py
> Fix KeyError resource_id

- CHANGELOG
- README.rst
- ckanext/xloader/plugin.py
> Populate function fix

- ckanext/xloader/jobs.py
- ckanext/xloader/tests/test_loader.py
> Cope with CKAN 2.9+ with no revision tables

- requirements.txt
> Got rid of pdftables which is optional, unmaintained, and causes problems

- README.rst
- ckanext/xloader/cli.py
- setup.py
> add paster command to add existing column types to the Data Dictionary

- MANIFEST.in
> Manifest added so the pypi package includes html files

- README.rst
- ckanext/xloader/cli.py
Adds explicit mention of bulk load, as suggested in #88
> Improve docs to include batch load etc

- ckanext/xloader/jobs.py
Changes include:
- write file hash back to the resource using resource_patch
- call the logic layer to update resource
> Update resource hash after load to datastore

- README.rst
ckanext-xloader 0.7.0 supports CKAN 2.9 (and Python 3)
> Update documentation for ckan 2.9

- .github/workflows/test.yml
- pip-requirements.txt
- requirements.txt
Delete pip-requirements.txt file which included unrelated requirements
@kowh-ai do you know why this file was created when a `requirements.txt` file already existed?
> Consolidate requirements.txt file

- README.rst
Updated command in README file to run the worker.
> Updated command in readme file

- ckanext/xloader/tests/samples/mixed_numeric_string_sample.csv
- ckanext/xloader/tests/test_loader.py
feat(tests): added type guess on mixed integers;
- More tests.
> Add Mixed Integers Type Guessing to NUMERIC Tests

- CHANGELOG
- README.md
- ckanext/xloader/action.py
- ckanext/xloader/config_declaration.yaml
- ckanext/xloader/plugin.py
- ckanext/xloader/schema.py
- ckanext/xloader/utils.py
squash(pr): 200;
- Squashed version of https://github.com/ckan/ckanext-xloader/pull/200.
> Validation Extension Support (Squashed)

- CHANGELOG
- ckanext/xloader/jobs.py
- ckanext/xloader/tests/test_jobs.py
- test.ini
squash(pr): 223;
- Squash of https://github.com/ckan/ckanext-xloader/pull/223
> RQ Job Timeout Handling (Squashed)

- MANIFEST.in
Fixes #244
https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html
need to include the extra files in packaging.
> fix: #244 include static webassets on packaging

- .flake8
- ckanext/xloader/jobs.py
- ckanext/xloader/loader.py
- ckanext/xloader/plugin.py
- ckanext/xloader/tests/test_jobs.py
- ckanext/xloader/tests/test_loader.py
- ckanext/xloader/tests/test_plugin.py
- Fix whitespace, indentation, unused variables, duplicate function
- Refactor to extract identical function definitions
> fix Flake8 complaints
