ckan/ckanext-xloader

ckanext/xloader/tests/test_loader.py
This varies between ckan versions
=> Fix test to do with the detail of indexing a csv row

ckanext/xloader/cli.py, ckanext/xloader/controllers.py, ckanext/xloader/jobs.py, ckanext/xloader/plugin.py
The CLI now doesn't send non-configured formats (e.g. PDFs), which brings it into line with the automated submissions when you add a resource to CKAN.
If you really want to submit PDFs etc then you can use the `--ignore-format` parameter
```
paster --plugin=xloader xloader submit all --ignore-format
```
Also a couple of change to options:
`--dry-run` added
`--force` removed - it never did anything (files are always reloaded since hash checking is not working)
I've also done some refactoring in the CLI code.
=> Dont submit resources with non-xloader formats with CLI

ckanext/xloader/loader.py, ckanext/xloader/tests/samples/column_names.csv, ckanext/xloader/tests/test_loader.py
Fixes #65 
TODO Still considering whether it's better to do this in the session.execute line instead, like is done in datastore's backend.
However datastore doesn't handle the percent perfectly yet, so that needs a fix too.
=> Fix for percent in column name

bin/travis-build.bash, ckanext/xloader/tests/test_jobs.py
Master now defaults to python3 requirements, without pylons
=> Fix build - master is python3 requirements

README.rst
Closes #17
Seems reasonable enough to put this small amount of job data into the
main ckan db. (The db tables get initialized during first xload.)
=> Use CKAN db to store jobs

ckanext/xloader/jobs.py
Fixes #93 
If CKAN hasn't quite added the resource yet, then we expect a 404,
causing a NotFound exception. So that is now caught and causes a delayed
retry. I'll keep JobError in there too, in case CKAN is being
unresponsive or connectivity is down for a moment.
=> Fix the retry of getting resource from CKAN

requirements.txt
Fixes https://github.com/ckan/ckanext-xloader/issues/125
`pip-requirements.txt` had the six module requirement to be >= 1.12 but not `requirements.txt`
The 'ensure_text' attribute was added to `six 1.12`
=> requirements.txt needs the six module to be >= 1.12

.github/workflows/test.yml, ckanext/xloader/jobs.py
Fixes Issue: https://github.com/ckan/ckanext-xloader/issues/126
This fixes a problem where a "KeyError: 'user'" error occurs during the update of the resource status - the context passed is missing "user info" and so errors out
=> Send user context to the resource patch function in patch.py

README.rst, ckanext/xloader/jobs.py
Adding `ckanext.xloader.ssl_verify` config to the README file.
Also I did a small refactor to use `toolkit.asbool()` to parse the config settings to have a consistent behavior with all other extensions. (ie, It wasn't parsing a `false` value)
=> Document ssl_verify config

ckanext/xloader/jobs.py
When working locally and using self signed certificates the POST request to `xloader_hook` fails to verify the certificate. This makes the job to never be updated to complete status after finishing.
I'm adding the `verify=SSL_VERIFY` parameter as we have in the `requests.get(...)` method.
=> Add ssl_verify option to callback_xloader_hook

ckanext/xloader/jobs.py
When using Python 3 the DataTooBigError workflow fails with the following error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/ckanext/xloader/jobs.py", line 76, in xloader_data_into_datastore
xloader_data_into_datastore_(input, job_dict)
File "/usr/local/lib/python3.8/dist-packages/ckanext/xloader/jobs.py", line 156, in xloader_data_into_datastore_
tmp_file, file_hash = _download_resource_data(resource, data, api_key,
File "/usr/local/lib/python3.8/dist-packages/ckanext/xloader/jobs.py", line 298, in _download_resource_data
tmp_file.write(line + '\n')
TypeError: can't concat str to bytes
```
The error is because `response.iter_lines()` returns a byte object, so we need to prefix `\n`.
=> Fix byte - str concat

ckanext/xloader/jobs.py
According to the docs:
*If you set `stream` to `True` when making a request, Requests cannot release the connection back to the pool unless you consume all the data or call `Response.close`. This can lead to inefficiency with connections.*
https://docs.python-requests.org/en/master/user/advanced/#body-content-workflow
This PR closes the connection when the previous conditions are not met.
=> Stream request needs to be explicited closed

ckanext/xloader/jobs.py, ckanext/xloader/plugin.py
This includes two 2.9 fixes (it does not include python 3 support related changes)
Commit messages have all details but the summary is:
1. Pass ignore_auth on action calls
2. Refactor plugin interfaces to avoid transaction error (Same as  ckan/ckan#5173)
=> CKAN 2.9 fixes

ckanext/xloader/action.py, ckanext/xloader/job_exceptions.py, ckanext/xloader/tests/test_action.py
Encode timestamps as strings on `xloader_status` call otherwise there is an error when trying to return the API JSON value.
This also includes a small fix to correctly report exceptions in stdout (40da6c6d8224907ad4798e0b4f97cdea64f65ce5)
=> Fix xloader status timestamps

ckanext/xloader/plugin.py
Enabling xloader causes an exception at the end of the dataset creation process, when submitting the resources.
So .. i was following @amercader 's  work on [5137](https://github.com/ckan/ckan/pull/5173)
=> fix xloader exceptions

README.rst
Fixes: 
```
Usage: ckan [OPTIONS] COMMAND [ARGS]...
Error: No such command 'submit'.
```
=> Add missing xloader command option

.github/workflows/test.yml, ckanext/xloader/action.py, ckanext/xloader/loader.py, requirements.txt
Python 3 support requires using `builtins` in commit https://github.com/open-data/ckanext-xloader/commit/8c43ceed879af9934dd843a36ab7c68d9a0535c8#diff-b0f564951458e386ad6106e20fa8938150638c260b1921aceba34dae89d04d58. Adding `future` to the requirements to avoid ImportError.
=> add future to requirements.txt

.github/workflows/test.yml, ckanext/xloader/jobs.py, ckanext/xloader/plugin.py, ckanext/xloader/tests/fixtures.py, ckanext/xloader/tests/test_jobs.py, ckanext/xloader/tests/test_loader.py, conftest.py
This PR is to support CKAN 2.10
Upstream ticket: https://github.com/ckan/ckan/issues/6787
- Fixed SQLAlchemy syntax that fails in `1.4`
- Add backwards compatibility for IResourceController methods.
- Add `conftest.py` file so we can use custom fixtures.
=> Add support for 2.10

ckanext/xloader/action.py
At the moment service makes a request to a `ckan.site_url` when a job finishes. If the CKAN app is mounted using `ckan.root_path`, the job is never marked as finished. 
It doesn't hurt much but creates some inconveniences. For example, default previews are not created.
=> Add root path to callback_url

pip-requirements.txt
`ckantoolkit` is backward-compatible, so it's safe to use newer versions. 
In addition, v0.0.4 didn't have a `unicode_safe` validator, thus `ckanext-xloader` with the pinned version of `ckantoolkit` may break environments after migration to CKAN v2.10.
=> Do not pin ckantoolkit version

ckanext/xloader/loader.py
In case messytables by default is off and one supplies a non-CSV file, the delimiter detection fails with a UnicodeDecodeError as it tries to parse the binary data (I presume). By catching that error and raising a LoadError instead, subsequent code picks it up and uses messytables as a fallback option.
=> Raise loadererror when the delimiter cannot be detected

.flake8, .github/workflows/test.yml, .gitignore, README.rst, ckanext/xloader/action.py, ckanext/xloader/command.py, ckanext/xloader/db.py, ckanext/xloader/job_exceptions.py, ckanext/xloader/jobs.py, ckanext/xloader/loader.py, ckanext/xloader/plugin.py, ckanext/xloader/schema.py, ckanext/xloader/tests/fixtures.py, ckanext/xloader/tests/test_jobs.py, ckanext/xloader/tests/test_loader.py, ckanext/xloader/tests/test_plugin.py, setup.py
- Fix typos
- Use 'six' for greater compatibility/consistency
- Use parameterised logging instead of formatting up-front
- Add a test for byte decoding problems
=> Cleanup from QGOV fork

ckanext/xloader/templates/xloader/resource_data.html
allow other extensions to add custom business logic to display the "Upload to DataStore" button
=> wrap "Upload to DataStore" button in a block

ckanext/xloader/action.py
Found issues while parsing the `last_updated` date from the `task_status` table.
- The fix includes parsing the `last_updated` date without microseconds as ckan APIs are not promising the date will always include microseconds.
Error logs
```
Traceback (most recent call last):
File "/usr/lib/ckan/odp/src/ckanext-datastore-refresh/ckanext/datastore_refresh/cli.py", line 56, in dataset
_submit_resource(pkg_dict, res, context)
File "/usr/lib/ckan/odp/src/ckanext-datastore-refresh/ckanext/datastore_refresh/cli.py", line 117, in _submit_resource
success = tk.get_action("xloader_submit")(context, data_dict)
File "/usr/lib/ckan/odp/src/ckan/ckan/logic/__init__.py", line 504, in wrapped
result = _action(context, data_dict, **kw)
File "/usr/lib/ckan/odp/src/ckanext-xloader/ckanext/xloader/action.py" …
```
=> Fixed date parsing while fetching entries for task_status

ckanext/xloader/tests/test_jobs.py, test.ini
The current implementation is skipping `test_jobs.py` given its old and deprecated engineering.
This PR gives some love by refactoring them using modern CKAN fixtures.
@smotornyuk this is a small follow up of #180  that I have been working on this morning.
=> Refactor test_jobs.py

ckanext/xloader/plugin.py
fix(dev): use `IDomainObjectModification` implementation;
- Use `IDomainObjectModification` instead of `IResourceUrlChange` for automagic exception handling.
Currently, the `notify` method from the `IResourceUrlChange` implementation is assuming that the Resource exists in the `resource_show` action call. But, at this point, other extensions (namely Validation running in sync mode) can delete the Resource from the session before it is committed. This would do a error here.
So using `IDomainObjectModification` instead, will automagically handle exceptions, logging them, and just passing so that normal operations will resume.
=> Use IDomainObjectModification Implementation

ckanext/xloader/templates/xloader/resource_data.html, ckanext/xloader/utils.py, ckanext/xloader/views.py
Default to showing the first 50 and last 50 entries, with links to display more.
This dramatically improves page load times for very large resources.
=> Hide excessive numbers of resource_data log entries, #187

.flake8, ckanext/xloader/jobs.py, ckanext/xloader/loader.py, ckanext/xloader/parser.py, ckanext/xloader/plugin.py, ckanext/xloader/tests/ckan_setup.py, ckanext/xloader/tests/fixtures.py, ckanext/xloader/tests/samples/mixed_numeric_string_sample.csv, ckanext/xloader/tests/samples/sample_with_blanks.csv, ckanext/xloader/tests/samples/sample_with_mixed_quotes.csv, ckanext/xloader/tests/test_loader.py, ckanext/xloader/utils.py
- Fix fallback to 'str' type on columns that mix numeric and string.
- Fix parsing of empty strings as 'numeric' or 'timestamp', by converting them to None.
- Increase CSV sample size to ensure that quote characters are correctly guessed.
=> #182 Type guessing fixes

ckanext/xloader/command.py, ckanext/xloader/helpers.py, ckanext/xloader/plugin.py, ckanext/xloader/templates/package/resource_edit_base.html, ckanext/xloader/templates/package/resource_read.html, ckanext/xloader/templates/package/snippets/resource_item.html, ckanext/xloader/templates/package/snippets/resources.html, ckanext/xloader/utils.py
feat(templates): conditional DataStore tab;
- Added helper for valid xloader formats.
- Added condition to display the DataStore tab in Resource Edit.
=> Conditional DataStore Tab in Resource Edit

ckanext/xloader/jobs.py, ckanext/xloader/loader.py, ckanext/xloader/utils.py
- Use TRUNCATE with a short locking timeout, instead of dropping and recreating a table, when data structure has not changed
- Retry jobs that fail due to locking problems
- Acquire write locks up front when updating resource metadata so race conditions don't cause deadlock
=> Make locking behaviour more robust

ckanext/xloader/templates/xloader/confirm_datastore_delete.html, ckanext/xloader/templates/xloader/resource_data.html, ckanext/xloader/views.py, requirements.txt
feat(views): added view and button to delete ds table;
- Added view to delete datastore table.
- Added button to delete a resource's datastore table.
Adds a button to the Xloader data page to delete a Resource's datastore table.
=> Delete Datastore Table Button

ckanext/xloader/loader.py, ckanext/xloader/tests/samples/sample_with_empty_lines.csv, ckanext/xloader/tests/test_loader.py
Configure Tabulator to ignore empty rows, #206
=> Skip empty lines instead of erroring

ckanext/xloader/action.py, ckanext/xloader/auth.py, ckanext/xloader/cli.py, ckanext/xloader/command.py, ckanext/xloader/helpers.py, ckanext/xloader/jobs.py, ckanext/xloader/tests/test_action.py, ckanext/xloader/tests/test_plugin.py
- Add CLI flag for loading immediately instead of queueing
- Allow sysadmins to specify an alternate queue to run on
=> add more options for maintainers to expedite XLoader runs, GitHub #202

ckanext/xloader/plugin.py
This is the fix of resource format key error
=> In plugin.py, there is an fix of resource format key error

.github/workflows/publish.yml
Relates to https://github.com/ckan/ckanext-xloader/issues/214 
Also requires pypi publishing configuration:
project_name: ckanext-xloader
owner: ckan
repository: ckanext-xloader
workflow_filename: publish.yml
environment: pypi
provider: github
https://pypi.org/manage/account/publishing/ is for new packages.
It needs to be setup at 
https://pypi.org/manage/project/ckanext-xloader/settings/publishing/
prefilled link for you: [here](https://pypi.org/manage/project/ckanext-xloader/settings/publishing/?project_name=ckanext-xloader&owner=ckan&repository=ckanext-xloader&workflow_filename=publish.yml&environment=pypi&provider=github)
=> feat: Add pypi cicd publish via github action via environment controls

.github/workflows/publish.yml
- Remove unwanted 'v' from tag pattern
- Fix environment parameter to have a default value when automatically triggered
- Add validation that tag version matches Python version
=> Fix automated PyPI publishing

.github/workflows/publish.yml, .github/workflows/test.yml, README.md, ckanext/xloader/db.py, ckanext/xloader/loader.py, ckanext/xloader/tests/test_loader.py
Compatibility with the new SQLAlchemy version tested against [this PR](https://github.com/ckan/ckan/pull/8410).
=> SQLAlchemy v2 support

ckanext/xloader/jobs.py
Fix for compatibility with CKAN Table Designer feature
=> Avoid loading R/W datastore resources

ckanext/xloader/jobs.py
This PR adds support for the new "apitoken_header_name" CKAN Config, in which you can specify alternative header for CKAN API Tokens.
This is an issue, when your CKAN instances are under Basic HTTP Authentication, which breaks the default "Authorization" header and as a result, uploading doesn't work and return 403 HTTP.
Those changes make sure that Xloader takes into account the changed Header for accepting CKAN API Keys.
=> Fix: Support CKAN 2.11.x Config apitoken_header_name - default to 'Authorization'

.github/workflows/test.yml
=> chore: uplift redis container from v3 to v7 as rq 2.0.0 drops below v4

ckanext/xloader/helpers.py, ckanext/xloader/job_exceptions.py, ckanext/xloader/jobs.py, ckanext/xloader/loader.py, ckanext/xloader/schema.py, ckanext/xloader/tests/samples/simple-with-extra-column.csv, ckanext/xloader/tests/test_action.py, ckanext/xloader/tests/test_jobs.py, ckanext/xloader/tests/test_loader.py, ckanext/xloader/tests/test_utils.py, ckanext/xloader/utils.py
Refine the COPY vs Tabulator behaviour:
- If fields are unchanged, truncate and reuse the datastore table.
- If field names are unchanged but types have changed, drop and recreate the table but preserve the Data Dictionary.
- If field names or counts have changed, fall back to Tabulator since we need to re-guess the types.
Also includes a Flake8 cleanup and ensuring temporary files are deleted.
=> Backport features from QGOV fork
